# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Test with Gradle N2

on:
  push:
     branches:
       - '**'

jobs:
  gradle_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Git Checkout



    - uses: mstachniuk/ci-skip@v1
      with:
         fail-fast: true
         commit-filter: '[ci-skip]'
    - name: Verification
      run: |
           echo "The previous step should exiting with 42 code and this code should not run"





    - name: Java installieren
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: gradle test
      run: ./gradlew test

    - name: gradle check
      run: ./gradlew check



  gradle_check:
    runs-on: ubuntu-latest
    needs: gradle_test
    steps:
    - uses: actions/checkout@v1
      name: Git Checkout

    - name: Java installieren
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: gradle check
      run: ./gradlew check
